name: Deploy docs website

on:
  schedule:
    - cron: '13 */3 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [build_docs]

jobs:
  publish:
    runs-on: [self-hosted, func-tester-aarch64]
    steps:
      - name: Check out docs repo
        uses: actions/checkout@v3
        with:
          repository: ClickHouse/clickhouse-docs
          path: ./
      - name: Download Reference Doc
        run:  |
          curl https://codeload.github.com/ClickHouse/ClickHouse/tar.gz/master | tar -xz -C ./ --strip=2 "ClickHouse-master/docs/"
          cp -R ./en docs
          cp -R ./ru docs/
          cp -R ./zh docs/
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '>=16.14'
      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn build
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_assets: '.github'
          cname: docs-content.clickhouse.tech
          publish_branch: gh-pages
          publish_dir: ./build
          destination_dir: docs
